### PR TITLE
Merge the Match List Feature into Develop

### PR DESCRIPTION
**Pull request by billymcd**
Match list and display page for matches are done. Some more details about the matched user could be added, but the current implementation should meet the UATs for this feature. To check the date ordering, you may use username: billy1 password: billy1, or any other account that has more than one successful match. There is a persistent bug with the buttons displaying the matched accounts for flatees, however this is a display bug and doesn't prevent it from meeting the DoD.

### CODE REVIEW

**Comment by finn-stainton** [comment]
image
Should there be a better title and explanation that a user doesn't have any matches?

**Comment by billymcd** [comment]
Hmm yeah, that's a good idea actually. Will work on it

**Comment by billymcd** [comment]
How's this

https://user-images.githubusercontent.com/85812885/136162330-bc23261c-2da3-4dae-842e-7c4d08c77456.png

**Comment by billymcd** [comment]
Just pushed a new commit, changed the title and the display for no matches as per your suggestion. Also fixed a bug that popped up while I was doing so.

**Comment by finn-stainton** [comment]
image

**Pull request merged**
